### ISSUE TITLE
Ionic & or NativeScript ? 

### ISSUE THREAD

**Issue by nigel-dewar** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#10]
Hi Fabian, WOW!! This is truley amazing what you have done here with this.

I was wondering if any figure plans to expand this repo out to include Ionic & or NativeScript ?

Cheers

**Comment by FabianGosebrink** [comment]
Hey @nigel-dewar 

not yet, but this repo is also able to do cross-platform builds. So you can build cordova-apps with this which can be easily used in ionic-solutions.

BR

Fabian

**Comment by nigel-dewar** [comment]
Thanks Fabian.

ill give it a shot.

your work is amazing mate.. I'll def be following your work. Cheers

**Comment by FabianGosebrink** [comment]
@nigel-dewar thank you so much. I really appreciate that.
