### ISSUE TITLE
Is this possible

### ISSUE THREAD

**Issue by aqibshehzad** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#13]
I am not posting a bug, I am writing to know the answer of my question, can this is possible that i have client app running of some machine and server on another and i want configure it with CORS to communicate and with the configuration of signalr in angular app and server one.

FIrst of all can this is possible , if possible then how it can be achieved.

can you provide me the demo app for this purpose

**Comment by FabianGosebrink** [comment]
You can configure CORS like the way you want. In this demo I allowed any origin, header, etc. In a real world app this would be different and only allow the values you want to.
