### ISSUE TITLE
Npm start does not work

### ISSUE THREAD

**Issue by mkzrt** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#15]
"npm start" command gives some errors:

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path D:\Repository\Downloads\ASPNETCore-Angular-SignalR-Typescript-master\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

**Comment by FabianGosebrink** [comment]
Have you done an `npm install` before?

**Comment by mkzrt** [comment]
Reinstall the node_modules solved my problem. Thanks.
