### ISSUE TITLE
signalr.d.ts

### ISSUE THREAD

**Issue by Sn3b** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#3]
Where does your signalr.d.ts file come from?

Did you write yourself? Was it generated? Does it come from any public repository?

**Comment by FabianGosebrink** [comment]
Got it from here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/signalr/signalr.d.ts

but I edited it commenting out something at the end of the document

**Comment by Sn3b** [comment]
Yeah I found it thanks. You probably had to comment something in the jquery typing file to avoid some error, but you could also replace the type of $ from JQueryStatic to cssSelectorHelper.
