### ISSUE TITLE
Data not refreshed in IE

### ISSUE THREAD

**Issue by gertadriaensen** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#5]
Hello,

I have implemented just a solution like you and everything is working perfect with SignalR to send updates to the client.
The only problem I have is that it is not working in IE but only in Chrome and Firefox. I am using IE 11 at the moment.

**Comment by FabianGosebrink** [comment]
Hey gertadriaensen,

I am facing the same issue. My only explanation so far is that IE is simply not ready yet with SignalR in this kind of version. I have to say that it slightly works in IE, but I get updates waaay slower than in the other browsers.

Regards

Fabian

**Comment by gertadriaensen** [comment]
The problem in IE is that it is not refreshing by itself. When I click a button on the page which has an Angular action that the data is showed.

How did you get it to work within IE?

**Comment by FabianGosebrink** [comment]
I used Edge for testing and the code in this repo :)

**Comment by gertadriaensen** [comment]
I am using IE11 and this is not working for me. Any ideas?

**Comment by gertadriaensen** [comment]
It is working now. I am starting the connection within a longpolling transport:

```
private startConnection(): void {
        this.connection.start({ transport: 'longPolling' } ).done((data) => {
            //console.log('Now connected ' + data.transport.name + ', connection ID= ' + data.id);
        }).fail((error) => {
            //console.log('Could not connect ' + error);
        });
    }

```

Check also this link:
http://www.asp.net/signalr/overview/getting-started/introduction-to-signalr

**Comment by FabianGosebrink** [comment]
Hey gertadriaensen,

yeah, I know this source. But what you are doing is forcing the longpolling-method to all browsers. I wanted to avoid this although it works in IE. But as long as the support in SignalR is not that good it's a solution :)

**Comment by gertadriaensen** [comment]
Is it possible to do this only for IE?

I know there is something like this: connection.start({ transport: ['webSockets','longPolling'] });

**Comment by FabianGosebrink** [comment]
You can check for the browser in a way and react on that...if this is a nice solution...I dont think so ;-)
