### ISSUE TITLE
ASP.NET Core SignalR beta package at MyGet

### ISSUE THREAD

**Issue by cveld** [FabianGosebrink/ASPNETCore-Angular-SignalR-Typescript#7]
I see you have forked the SignalR source code from GitHub in order to get it all up and running. Have you also assessed the packages that live on MyGet?

Add the following source to your nuget package sources through Tools -> Options
https://www.myget.org/F/aspnetmaster/api/v3/index.json

And add the following MyGet package to your project (maybe you need others as well):
Microsoft.AspNetCore.SignalR.Server

**Comment by FabianGosebrink** [comment]
Added new sources and getting it over myget now
